### ISSUE TITLE
If you switch between the Barrett quickly while firing you never have to reload.

### ISSUE THREAD

**Issue by michaeljcalkins** [michaeljcalkins/rangersteve-ideas#212] opened 2017-01-19 04:26 UTC
Example: http://i.imgur.com/IEWCGk2.gif

Using the Barrett and Desert Eagle
My ammo count for both guns goes down

Push Q and left click alternating quickly before the reload can start.

**Comment by And-re** [comment] 2017-01-19 10:11
duplicate of #154

**Comment by And-re** [comment] 2017-01-21 22:10
https://github.com/michaeljcalkins/rangersteve/pull/355

**Closed by And-re** 2017-01-21 22:10 UTC
Labels: Priority: Medium, Type: Bug
