### ISSUE TITLE
BUG: Enemy immediately respawned in same location

### ISSUE THREAD

**Issue by DrEvilGenius** [michaeljcalkins/rangersteve-ideas#181] opened 2017-01-03 03:18 UTC
https://gyazo.com/0a4bbaec9b0893f46b507d93162753ab

**Comment by michaeljcalkins** [comment] 2017-01-08 21:40
@DrEvilGenius I'm not sure exactly what's happening here. Do you have another video or a way to reproduce?

**Comment by michaeljcalkins** [comment] 2017-01-12 17:10
Duplicate of #175

**Closed by michaeljcalkins** 2017-01-12 17:10 UTC
Labels: Priority: High, Status: More Info Needed, Type: Bug
